#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("nyWeatherApp.Droid.Resource", IsApplication=true)]

namespace nyWeatherApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom1_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int theme_custom_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int theme_devicedefault_background = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int GetWeatherButton = 2131165188;
			
			// aapt resource value: 0x7f070011
			public const int HumidityText = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int ResultsTable = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int ResultsTitle = 2131165189;
			
			// aapt resource value: 0x7f070019
			public const int SunriseText = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int SunsetText = 2131165212;
			
			// aapt resource value: 0x7f070009
			public const int TempText = 2131165193;
			
			// aapt resource value: 0x7f070015
			public const int VisibilityText = 2131165205;
			
			// aapt resource value: 0x7f07000d
			public const int WindText = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int ZipCodeEdit = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int ZipCodeLabel = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int relativeLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int tableRow1 = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int tableRow2 = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int tableRow3 = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int tableRow4 = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int tableRow5 = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int tableRow6 = 2131165210;
			
			// aapt resource value: 0x7f070008
			public const int textView21 = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int textView22 = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int textView23 = 2131165200;
			
			// aapt resource value: 0x7f07000a
			public const int textView26 = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int textView27 = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int textView28 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int textView34 = 2131165204;
			
			// aapt resource value: 0x7f070018
			public const int textView40 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int textView46 = 2131165211;
			
			// aapt resource value: 0x7f070016
			public const int textView50 = 2131165206;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Custom1 = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
